#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/sm8635-common

PRODUCT_COPY_FILES += \
    vendor/xiaomi/sm8635-common/proprietary/odm/etc/Keyboard_Upgrade_0x01.bin:$(TARGET_COPY_OUT_ODM)/etc/Keyboard_Upgrade_0x01.bin \
    vendor/xiaomi/sm8635-common/proprietary/odm/etc/Keyboard_Upgrade_0x10.bin:$(TARGET_COPY_OUT_ODM)/etc/Keyboard_Upgrade_0x10.bin \
    vendor/xiaomi/sm8635-common/proprietary/odm/etc/Keyboard_Upgrade_0x61.bin:$(TARGET_COPY_OUT_ODM)/etc/Keyboard_Upgrade_0x61.bin \
    vendor/xiaomi/sm8635-common/proprietary/odm/etc/TouchPad_Upgrade_0x04.bin:$(TARGET_COPY_OUT_ODM)/etc/TouchPad_Upgrade_0x04.bin \
    vendor/xiaomi/sm8635-common/proprietary/odm/etc/audio/hrtf5c.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/hrtf5c.bin \
    vendor/xiaomi/sm8635-common/proprietary/odm/etc/audio/sku_cliffs/adsp_sleep_monitor.conf:$(TARGET_COPY_OUT_ODM)/etc/audio/sku_cliffs/adsp_sleep_monitor.conf \
    vendor/xiaomi/sm8635-common/proprietary/odm/etc/audio/sku_cliffs/mixer_paths_cliffs_mtp.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/sku_cliffs/mixer_paths_cliffs_mtp.xml \
    vendor/xiaomi/sm8635-common/proprietary/odm/etc/audio/sku_cliffs/mixer_paths_overlay_dynamic.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/sku_cliffs/mixer_paths_overlay_dynamic.xml \
    vendor/xiaomi/sm8635-common/proprietary/odm/etc/audio_policy_engine_configuration.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_policy_engine_configuration.xml \
    vendor/xiaomi/sm8635-common/proprietary/odm/etc/audio_policy_engine_default_stream_volumes.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_policy_engine_default_stream_volumes.xml \
    vendor/xiaomi/sm8635-common/proprietary/odm/etc/audio_policy_engine_product_strategies.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_policy_engine_product_strategies.xml \
    vendor/xiaomi/sm8635-common/proprietary/odm/etc/init.panel_info.sh:$(TARGET_COPY_OUT_ODM)/etc/init.panel_info.sh \
    vendor/xiaomi/sm8635-common/proprietary/odm/etc/init/init.awinic.rc:$(TARGET_COPY_OUT_ODM)/etc/init/init.awinic.rc \
    vendor/xiaomi/sm8635-common/proprietary/odm/etc/init/init.cirrus.rc:$(TARGET_COPY_OUT_ODM)/etc/init/init.cirrus.rc \
    vendor/xiaomi/sm8635-common/proprietary/odm/etc/init/init.foursemi.rc:$(TARGET_COPY_OUT_ODM)/etc/init/init.foursemi.rc \
    vendor/xiaomi/sm8635-common/proprietary/odm/etc/init/init.sia91xx.rc:$(TARGET_COPY_OUT_ODM)/etc/init/init.sia91xx.rc \
    vendor/xiaomi/sm8635-common/proprietary/odm/etc/init/init.xiaomi_hall.rc:$(TARGET_COPY_OUT_ODM)/etc/init/init.xiaomi_hall.rc \
    vendor/xiaomi/sm8635-common/proprietary/odm/etc/init/vendor.xiaomi.hw.touchfeature-service.rc:$(TARGET_COPY_OUT_ODM)/etc/init/vendor.xiaomi.hw.touchfeature-service.rc \
    vendor/xiaomi/sm8635-common/proprietary/odm/etc/init/vendor.xiaomi.sensor.citsensorservice.aidl.rc:$(TARGET_COPY_OUT_ODM)/etc/init/vendor.xiaomi.sensor.citsensorservice.aidl.rc \
    vendor/xiaomi/sm8635-common/proprietary/odm/etc/izat_device.conf:$(TARGET_COPY_OUT_ODM)/etc/izat_device.conf \
    vendor/xiaomi/sm8635-common/proprietary/odm/etc/touch/stylus_game_config.json:$(TARGET_COPY_OUT_ODM)/etc/touch/stylus_game_config.json \
    vendor/xiaomi/sm8635-common/proprietary/odm/etc/ueventd.rc:$(TARGET_COPY_OUT_ODM)/etc/ueventd.rc \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/CAMERA_ICP.b00:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b00 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/CAMERA_ICP.b01:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b01 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/CAMERA_ICP.b02:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b02 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/CAMERA_ICP.b03:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b03 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/CAMERA_ICP.b04:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b04 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/CAMERA_ICP.b05:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b05 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/CAMERA_ICP.b06:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b06 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/CAMERA_ICP.b07:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b07 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/CAMERA_ICP.b08:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b08 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/CAMERA_ICP.b09:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b09 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/CAMERA_ICP.b10:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b10 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/CAMERA_ICP.b11:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b11 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/CAMERA_ICP.b12:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b12 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/CAMERA_ICP.b13:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b13 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/CAMERA_ICP.b14:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b14 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/CAMERA_ICP.b15:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b15 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/CAMERA_ICP.b16:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b16 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/CAMERA_ICP.b17:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b17 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/CAMERA_ICP.b18:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b18 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/CAMERA_ICP.b19:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b19 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/CAMERA_ICP.b20:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b20 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/CAMERA_ICP.mbn:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.mbn \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/CAMERA_ICP.mdt:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.mdt \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/MCU_Upgrade.bin:$(TARGET_COPY_OUT_ODM)/firmware/MCU_Upgrade.bin \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass-lt.b00:$(TARGET_COPY_OUT_ODM)/firmware/evass-lt.b00 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass-lt.b01:$(TARGET_COPY_OUT_ODM)/firmware/evass-lt.b01 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass-lt.b02:$(TARGET_COPY_OUT_ODM)/firmware/evass-lt.b02 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass-lt.b03:$(TARGET_COPY_OUT_ODM)/firmware/evass-lt.b03 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass-lt.b04:$(TARGET_COPY_OUT_ODM)/firmware/evass-lt.b04 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass-lt.b05:$(TARGET_COPY_OUT_ODM)/firmware/evass-lt.b05 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass-lt.b06:$(TARGET_COPY_OUT_ODM)/firmware/evass-lt.b06 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass-lt.b07:$(TARGET_COPY_OUT_ODM)/firmware/evass-lt.b07 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass-lt.b08:$(TARGET_COPY_OUT_ODM)/firmware/evass-lt.b08 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass-lt.b09:$(TARGET_COPY_OUT_ODM)/firmware/evass-lt.b09 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass-lt.b10:$(TARGET_COPY_OUT_ODM)/firmware/evass-lt.b10 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass-lt.b11:$(TARGET_COPY_OUT_ODM)/firmware/evass-lt.b11 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass-lt.b12:$(TARGET_COPY_OUT_ODM)/firmware/evass-lt.b12 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass-lt.b13:$(TARGET_COPY_OUT_ODM)/firmware/evass-lt.b13 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass-lt.b14:$(TARGET_COPY_OUT_ODM)/firmware/evass-lt.b14 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass-lt.b15:$(TARGET_COPY_OUT_ODM)/firmware/evass-lt.b15 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass-lt.b16:$(TARGET_COPY_OUT_ODM)/firmware/evass-lt.b16 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass-lt.b17:$(TARGET_COPY_OUT_ODM)/firmware/evass-lt.b17 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass-lt.b18:$(TARGET_COPY_OUT_ODM)/firmware/evass-lt.b18 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass-lt.b19:$(TARGET_COPY_OUT_ODM)/firmware/evass-lt.b19 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass-lt.mbn:$(TARGET_COPY_OUT_ODM)/firmware/evass-lt.mbn \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass-lt.mdt:$(TARGET_COPY_OUT_ODM)/firmware/evass-lt.mdt \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass.b00:$(TARGET_COPY_OUT_ODM)/firmware/evass.b00 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass.b01:$(TARGET_COPY_OUT_ODM)/firmware/evass.b01 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass.b02:$(TARGET_COPY_OUT_ODM)/firmware/evass.b02 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass.b03:$(TARGET_COPY_OUT_ODM)/firmware/evass.b03 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass.b04:$(TARGET_COPY_OUT_ODM)/firmware/evass.b04 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass.b05:$(TARGET_COPY_OUT_ODM)/firmware/evass.b05 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass.b06:$(TARGET_COPY_OUT_ODM)/firmware/evass.b06 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass.b07:$(TARGET_COPY_OUT_ODM)/firmware/evass.b07 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass.b08:$(TARGET_COPY_OUT_ODM)/firmware/evass.b08 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass.b09:$(TARGET_COPY_OUT_ODM)/firmware/evass.b09 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass.b10:$(TARGET_COPY_OUT_ODM)/firmware/evass.b10 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass.b11:$(TARGET_COPY_OUT_ODM)/firmware/evass.b11 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass.b12:$(TARGET_COPY_OUT_ODM)/firmware/evass.b12 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass.b13:$(TARGET_COPY_OUT_ODM)/firmware/evass.b13 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass.b14:$(TARGET_COPY_OUT_ODM)/firmware/evass.b14 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass.b15:$(TARGET_COPY_OUT_ODM)/firmware/evass.b15 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass.b16:$(TARGET_COPY_OUT_ODM)/firmware/evass.b16 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass.b17:$(TARGET_COPY_OUT_ODM)/firmware/evass.b17 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass.b18:$(TARGET_COPY_OUT_ODM)/firmware/evass.b18 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass.b19:$(TARGET_COPY_OUT_ODM)/firmware/evass.b19 \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass.mbn:$(TARGET_COPY_OUT_ODM)/firmware/evass.mbn \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/evass.mdt:$(TARGET_COPY_OUT_ODM)/firmware/evass.mdt \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/gen70900_zap.mbn:$(TARGET_COPY_OUT_ODM)/firmware/gen70900_zap.mbn \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/gen71100_zap.mbn:$(TARGET_COPY_OUT_ODM)/firmware/gen71100_zap.mbn \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/vpu20_2v.mbn:$(TARGET_COPY_OUT_ODM)/firmware/vpu20_2v.mbn \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/vpu20_2v_unsigned.mbn:$(TARGET_COPY_OUT_ODM)/firmware/vpu20_2v_unsigned.mbn \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/vpu20_4v.mbn:$(TARGET_COPY_OUT_ODM)/firmware/vpu20_4v.mbn \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/vpu20_4v_unsigned.mbn:$(TARGET_COPY_OUT_ODM)/firmware/vpu20_4v_unsigned.mbn \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/vpu30_2v.mbn:$(TARGET_COPY_OUT_ODM)/firmware/vpu30_2v.mbn \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/vpu30_2v_unsigned.mbn:$(TARGET_COPY_OUT_ODM)/firmware/vpu30_2v_unsigned.mbn \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/vpu33_4v.mbn:$(TARGET_COPY_OUT_ODM)/firmware/vpu33_4v.mbn \
    vendor/xiaomi/sm8635-common/proprietary/odm/firmware/vpu33_4v_unsigned.mbn:$(TARGET_COPY_OUT_ODM)/firmware/vpu33_4v_unsigned.mbn \
    vendor/xiaomi/sm8635-common/proprietary/system/etc/sysconfig/qti_whitelist.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/qti_whitelist.xml \
    vendor/xiaomi/sm8635-common/proprietary/system_ext/etc/dpm/dpm.conf:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/dpm/dpm.conf \
    vendor/xiaomi/sm8635-common/proprietary/system_ext/etc/init/dpmd.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/dpmd.rc \
    vendor/xiaomi/sm8635-common/proprietary/system_ext/etc/init/tcmd.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/tcmd.rc \
    vendor/xiaomi/sm8635-common/proprietary/system_ext/etc/init/vendor.qti.qccsyshal_aidl-service.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/vendor.qti.qccsyshal_aidl-service.rc \
    vendor/xiaomi/sm8635-common/proprietary/system_ext/etc/init/wfdservice.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/wfdservice.rc \
    vendor/xiaomi/sm8635-common/proprietary/system_ext/etc/permissions/com.qti.dpmframework.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qti.dpmframework.xml \
    vendor/xiaomi/sm8635-common/proprietary/system_ext/etc/permissions/dpmapi.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/dpmapi.xml \
    vendor/xiaomi/sm8635-common/proprietary/system_ext/etc/permissions/wfd-system-ext-privapp-permissions-qti.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/wfd-system-ext-privapp-permissions-qti.xml \
    vendor/xiaomi/sm8635-common/proprietary/system_ext/etc/seccomp_policy/tcmd.policy:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/seccomp_policy/tcmd.policy \
    vendor/xiaomi/sm8635-common/proprietary/system_ext/etc/seccomp_policy/wfdservice64.policy:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/seccomp_policy/wfdservice64.policy \
    vendor/xiaomi/sm8635-common/proprietary/system_ext/etc/wfdconfigsink.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/wfdconfigsink.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/Hapticsconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/Hapticsconfig.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/cliffs_mtp/MTP_cliffs_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/cliffs_mtp/MTP_cliffs_acdb_cal.acdb \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/cliffs_mtp/MTP_cliffs_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/cliffs_mtp/MTP_cliffs_workspaceFileXml.qwsp \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/cliffs_mtp_wcd9395_cliffs7/MTP_cliffs7_wcd9395_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/cliffs_mtp_wcd9395_cliffs7/MTP_cliffs7_wcd9395_acdb_cal.acdb \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/cliffs_mtp_wcd9395_cliffs7/MTP_cliffs7_wcd9395_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/cliffs_mtp_wcd9395_cliffs7/MTP_cliffs7_wcd9395_workspaceFileXml.qwsp \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/cliffs_mtp_wsa883x_cliffs7/MTP_cliffs7_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/cliffs_mtp_wsa883x_cliffs7/MTP_cliffs7_acdb_cal.acdb \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/cliffs_mtp_wsa883x_cliffs7/MTP_cliffs7_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/cliffs_mtp_wsa883x_cliffs7/MTP_cliffs7_workspaceFileXml.qwsp \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/ffv_models/ffv__5.0.1_0.1__3.0.0_0.0__eai_2.10_enpu3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ffv_models/ffv__5.0.1_0.1__3.0.0_0.0__eai_2.10_enpu3.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/ffv_models/ffv__5.0.1_0.1__eai_2.10_enpu3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ffv_models/ffv__5.0.1_0.1__eai_2.10_enpu3.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/ffv_models/ffv__6.2.5_0.1__eai_3.4__enpu_v4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ffv_models/ffv__6.2.5_0.1__eai_3.4__enpu_v4.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/ffv_models/ffv__7.0.1_0.1__eai_3.4_enpu_v4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ffv_models/ffv__7.0.1_0.1__eai_3.4_enpu_v4.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__11.0.1.0_1.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.0__eai_3.4_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__11.0.1.0_1.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.0__eai_3.4_enpuv4.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.7_enpu3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.7_enpu3.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.36_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.36_enpu2.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.10.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.10.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.36_enpu2_comp.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.36_enpu2_comp.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.6.3_0.0__3.0.0_0.0__3.1.1.0_0.0__3.2.0_0.0__eai_2.7_enpu_v3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.6.3_0.0__3.0.0_0.0__3.1.1.0_0.0__3.2.0_0.0__eai_2.7_enpu_v3.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.6.3_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.0_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.6.3_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.0_enpuv4.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.6.5_0.0__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.6.5_0.0__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.20_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.20_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.20_0.0__3.0.0_0.0__eai_1.36_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.20_0.0__3.0.0_0.0__eai_1.36_enpu2.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.20_0.0__3.0.0_0.0__eai_3.4_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.20_0.0__3.0.0_0.0__eai_3.4_enpuv4.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.2_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.2_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.2_0.0__3.0.0_0.0__eai_1.36_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.2_0.0__3.0.0_0.0__eai_1.36_enpu2.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.5_0.0__3.0.0_0.0__3.1.1.0_0.0__3.2.0_0.0__eai_2.7_enpu_v3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.5_0.0__3.0.0_0.0__3.1.1.0_0.0__3.2.0_0.0__eai_2.7_enpu_v3.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.5_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.0_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.5_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.0_enpuv4.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.6_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.6_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.7_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.7_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.8_0.0__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.8_0.0__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.8_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.0_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.8_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.0_enpuv4.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.9.0_1.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.9.0_1.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.9.2_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.9.2_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.9.2_1.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.0__eai_3.4_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.9.2_1.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.0__eai_3.4_enpuv4.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__4.6.3_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__4.6.3_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__4.8.14_1.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__4.8.14_1.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__4.8.14_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__11.0.1.4_1.0__eai_3.4_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__4.8.14_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__11.0.1.4_1.0__eai_3.4_enpuv4.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__4.8.2_0.0__3.0.0_0.0__3.1.1.0_0.0__3.2.0_0.0__eai_2.7_enpu_v3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__4.8.2_0.0__3.0.0_0.0__3.1.1.0_0.0__3.2.0_0.0__eai_2.7_enpu_v3.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__4.8.3_0.0__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__4.8.3_0.0__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__4.8.4_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.0_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__4.8.4_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.0_enpuv4.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__4.8.4_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__4.8.4_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__8.0.2_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__8.0.2_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_1.36_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_1.36_enpu2.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_2.10_enpuv3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_2.10_enpuv3.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_3.4_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_3.4_enpuv4.pmd \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/apdr.conf:$(TARGET_COPY_OUT_VENDOR)/etc/apdr.conf \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/audio/sku_cliffs/audio_effects.conf:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_cliffs/audio_effects.conf \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/audio_cloud_control_white_list.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_cloud_control_white_list.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/audio_diag.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio_diag.cfg \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/batching.conf:$(TARGET_COPY_OUT_VENDOR)/etc/batching.conf \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/card-defs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/card-defs.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/charger_diag.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/charger_diag.cfg \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/charger_fw_fstab.qti:$(TARGET_COPY_OUT_VENDOR)/etc/charger_fw_fstab.qti \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/clstc_config_library.xml:$(TARGET_COPY_OUT_VENDOR)/etc/clstc_config_library.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/mwqem.conf:$(TARGET_COPY_OUT_VENDOR)/etc/cne/mwqem.conf \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/profileMwqem.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/profileMwqem.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile1.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile2.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile3.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile4.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile5.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile6.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile7.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile7.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile1.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile15.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile15.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile16.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile16.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile17.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile18.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile19.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile19.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile2.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile20.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile21.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile21.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile3.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile32.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile32.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile4.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile5.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile6.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile7.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile7.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile1.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile2.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile3.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile4.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile5.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile6.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile7.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile7.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/configstore/vpp.configstore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/configstore/vpp.configstore.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/data/nicm_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/nicm_config.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/data/tlpd_oem_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/tlpd_oem_config.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/default-permissions/com.qualcomm.qti.cne.xml:$(TARGET_COPY_OUT_VENDOR)/etc/default-permissions/com.qualcomm.qti.cne.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/default-permissions/vendor.qti.data.txpwradmin.xml:$(TARGET_COPY_OUT_VENDOR)/etc/default-permissions/vendor.qti.data.txpwradmin.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/display/DPU1010.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU1010.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/display/DPU1020.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU1020.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/display/DPU10__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU10__.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/display/DPU870.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU870.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/display/DPU9__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU9__.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/display/advanced_sf_offsets.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/advanced_sf_offsets.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/display/perf_hint_threshold.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/perf_hint_threshold.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/display/thermallevel_to_fps.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/thermallevel_to_fps.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/dolby/dax-default-spatializer.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default-spatializer.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/dpm_vndr/vendor.dpm.conf:$(TARGET_COPY_OUT_VENDOR)/etc/dpm_vndr/vendor.dpm.conf \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/eva/facedetection/bias.dat:$(TARGET_COPY_OUT_VENDOR)/etc/eva/facedetection/bias.dat \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/eva/facedetection/weight.dat:$(TARGET_COPY_OUT_VENDOR)/etc/eva/facedetection/weight.dat \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/eva/facelandmark/bias_1_1.dat:$(TARGET_COPY_OUT_VENDOR)/etc/eva/facelandmark/bias_1_1.dat \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/eva/facelandmark/bias_1_2.dat:$(TARGET_COPY_OUT_VENDOR)/etc/eva/facelandmark/bias_1_2.dat \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/eva/facelandmark/bias_2.dat:$(TARGET_COPY_OUT_VENDOR)/etc/eva/facelandmark/bias_2.dat \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/eva/facelandmark/bias_3_1.dat:$(TARGET_COPY_OUT_VENDOR)/etc/eva/facelandmark/bias_3_1.dat \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/eva/facelandmark/bias_3_2.dat:$(TARGET_COPY_OUT_VENDOR)/etc/eva/facelandmark/bias_3_2.dat \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/eva/facelandmark/weight_1_1.dat:$(TARGET_COPY_OUT_VENDOR)/etc/eva/facelandmark/weight_1_1.dat \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/eva/facelandmark/weight_1_2.dat:$(TARGET_COPY_OUT_VENDOR)/etc/eva/facelandmark/weight_1_2.dat \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/eva/facelandmark/weight_2.dat:$(TARGET_COPY_OUT_VENDOR)/etc/eva/facelandmark/weight_2.dat \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/eva/facelandmark/weight_3_1.dat:$(TARGET_COPY_OUT_VENDOR)/etc/eva/facelandmark/weight_3_1.dat \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/eva/facelandmark/weight_3_2.dat:$(TARGET_COPY_OUT_VENDOR)/etc/eva/facelandmark/weight_3_2.dat \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/eva/itof/tuning_params_sensor_type_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/eva/itof/tuning_params_sensor_type_1.json \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/external_camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/external_camera_config.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/gpfspath_oem_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gpfspath_oem_config.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/hrtf5c.bin:$(TARGET_COPY_OUT_VENDOR)/etc/hrtf5c.bin \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/android.hardware.bluetooth@1.1-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.1-service-qti.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/android.hardware.drm@1.1-service.wfdhdcp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.1-service.wfdhdcp.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/android.hardware.gatekeeper-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper-service-qti.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/android.hardware.security.keymint-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service-qti.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/cnd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/cnd.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/com.qualcomm.qti.wifidisplayhal@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/com.qualcomm.qti.wifidisplayhal@1.0-service.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/dataadpl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataadpl.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/dataqti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataqti.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/dms-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dms-service.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/dpmQmiMgr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dpmQmiMgr.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/feature_enabler_client.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/feature_enabler_client.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/hexlpservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hexlpservice.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/hw/init.batterysecret.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.batterysecret.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/hw/init.mi_thermald.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.mi_thermald.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/hw/init.qcom.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.qcom.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/hw/init.qti.kernel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.qti.kernel.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/hw/init.target.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.target.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/init.embmssl_server.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.embmssl_server.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/init.qccvendor.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qccvendor.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/init.qlm-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qlm-service.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/init.qti.graphics.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qti.graphics.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/init.qti.media.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qti.media.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/init.qti.qcv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qti.qcv.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/init.time_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.time_daemon.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/init.vendor.ins.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.ins.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/init.vendor.sensors.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.sensors.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/init.vendor.wlan.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.wlan.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/loc-launcher.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/loc-launcher.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/port-bridge.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/port-bridge.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/poweropt-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/poweropt-service.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/qdcmss.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qdcmss.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/qesdk-manager.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qesdk-manager.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/qesdk-secmanager.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qesdk-secmanager.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/qguard.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qguard.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/qmipriod.debug.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qmipriod.debug.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/qmipriod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qmipriod.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/qseecomd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qseecomd.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/qwesd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qwesd.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/shsusrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/shsusrd.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/ssgtzd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ssgtzd.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/trusteduilistener.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trusteduilistener.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.dpmd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.dpmd.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qsap.location.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qsap.location.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qsap.qapeservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qsap.qapeservice.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qsap.sensors.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qsap.sensors.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.adsprpc-guestos-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.adsprpc-guestos-service.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.camera.provider-service_64.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.camera.provider-service_64.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.cdsprpc-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.cdsprpc-service.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.diag_userdebug.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.diag_userdebug.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.hardware.alarm-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.alarm-service.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.hardware.display.color-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.display.color-service.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.hardware.dsp@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.dsp@1.0-service.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.hardware.factory-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.factory-service.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.hardware.factory@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.factory@1.0-service.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.hardware.iop@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.iop@2.0-service.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.hardware.limits-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.limits-service.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.hardware.perf2-hal-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.perf2-hal-service.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.hardware.secureprocessor.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.secureprocessor.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.hardware.secureprocessor@1.0.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.secureprocessor@1.0.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.hardware.sensorscalibrate-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.sensorscalibrate-service.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.hardware.servicetrackeraidl-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.servicetrackeraidl-service.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.hardware.trustedui-aidl-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.trustedui-aidl-service-qti.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.media.c2@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.media.c2@1.0-service.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.media.c2audio@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.media.c2audio@1.0-service.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.memory.pasrmanager-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.memory.pasrmanager-service.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.pasrknob@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.pasrknob@1.0-service.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.psiclient@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.psiclient@1.0-service.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.qspmhal-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.qspmhal-service.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.rmt_storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.rmt_storage.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.smp2p.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.smp2p.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.qti.tftp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.tftp.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.sensors.qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sensors.qti.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.sensors.sscrpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sensors.sscrpcd.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vendor.xiaomi.hardware.displayfeature_aidl-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.xiaomi.hardware.displayfeature_aidl-service.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vmmgr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vmmgr.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/vppservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vppservice.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/init/wfdvndservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wfdvndservice.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/kvh2xml.xml:$(TARGET_COPY_OUT_VENDOR)/etc/kvh2xml.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/lm/AdaptLaunchFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/AdaptLaunchFeature.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/lm/AppClassifierFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/AppClassifierFeature.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/lm/LightningLaunchesFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/LightningLaunchesFeature.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/lm/PreKillFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/PreKillFeature.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/lm/PrefAppsFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/PrefAppsFeature.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/lm/ProCompFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/ProCompFeature.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/lm/QAPE.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/QAPE.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/lm/QGPE.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/QGPE.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/lm/QGPEActionMap.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/QGPEActionMap.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/lm/SagtFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/SagtFeature.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/lm/SilkyScrollsFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/SilkyScrollsFeature.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/lm/prekill/prekill_2GB.data:$(TARGET_COPY_OUT_VENDOR)/etc/lm/prekill/prekill_2GB.data \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/lm/prekill/prekill_4GB.data:$(TARGET_COPY_OUT_VENDOR)/etc/lm/prekill/prekill_4GB.data \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/lm/prekill/prekill_6GB.data:$(TARGET_COPY_OUT_VENDOR)/etc/lm/prekill/prekill_6GB.data \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/lm/sPLHFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/sPLHFeature.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/lowi.conf:$(TARGET_COPY_OUT_VENDOR)/etc/lowi.conf \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/media_cliffs_v0/video_system_specs.json:$(TARGET_COPY_OUT_VENDOR)/etc/media_cliffs_v0/video_system_specs.json \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/media_cliffs_v1/video_system_specs.json:$(TARGET_COPY_OUT_VENDOR)/etc/media_cliffs_v1/video_system_specs.json \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/media_codecs_cliffs_v0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_cliffs_v0.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/media_codecs_cliffs_v1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_cliffs_v1.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/media_codecs_dolby_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_dolby_audio.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/media_codecs_muyu.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_muyu.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/media_codecs_performance_cliffs_v0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance_cliffs_v0.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/media_codecs_performance_cliffs_v1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance_cliffs_v1.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/media_codecs_performance_muyu.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance_muyu.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/media_profiles_V1_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_V1_0.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/media_profiles_cliffs_v0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_cliffs_v0.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/media_profiles_cliffs_v1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_cliffs_v1.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/media_profiles_muyu.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_muyu.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/media_profiles_uke.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_uke.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/mem_logger_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mem_logger_config.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/microphone_characteristics.xml:$(TARGET_COPY_OUT_VENDOR)/etc/microphone_characteristics.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/misound_asc_model.tflite:$(TARGET_COPY_OUT_VENDOR)/etc/misound_asc_model.tflite \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/models/acd/environment.eai:$(TARGET_COPY_OUT_VENDOR)/etc/models/acd/environment.eai \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/models/acd/event.eai:$(TARGET_COPY_OUT_VENDOR)/etc/models/acd/event.eai \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/models/acd/music.eai:$(TARGET_COPY_OUT_VENDOR)/etc/models/acd/music.eai \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/models/acd/speech.eai:$(TARGET_COPY_OUT_VENDOR)/etc/models/acd/speech.eai \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/models/vui/sm8_gr1UsPdk6XsMfcn220819Enpu4FloateAIv34.uim:$(TARGET_COPY_OUT_VENDOR)/etc/models/vui/sm8_gr1UsPdk6XsMfcn220819Enpu4FloateAIv34.uim \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/models/vui/sm8_gr3UsMFCN230612eAIv34ENPUv4Float.uim:$(TARGET_COPY_OUT_VENDOR)/etc/models/vui/sm8_gr3UsMFCN230612eAIv34ENPUv4Float.uim \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/perf/avcsysnodesconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/avcsysnodesconfigs.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/perf/commonresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/commonresourceconfigs.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/perf/commonsysnodesconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/commonsysnodesconfigs.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/perf/exceptionrecoveryconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/exceptionrecoveryconfig.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/perf/perfboostsconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfboostsconfig.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/perf/perfboostselection.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfboostselection.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/perf/perfconfigstore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfconfigstore.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/perf/targetavcsysnodesconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetavcsysnodesconfigs.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/perf/targetconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetconfig.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/perf/targetresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetresourceconfigs.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/perf/targetsysnodesconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetsysnodesconfigs.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/perf/testcommonresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/testcommonresourceconfigs.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/perf/testtargetresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/testtargetresourceconfigs.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/perf/thermal-boost.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf/thermal-boost.conf \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/perf/thermalbreakboostconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/thermalbreakboostconfig.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/permissions/vendor.qti.hardware.factory.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/vendor.qti.hardware.factory.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/public.libraries.txt:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/pwr/AODPowerOptFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwr/AODPowerOptFeature.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/pwr/GamePowerOptFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwr/GamePowerOptFeature.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/pwr/OffScreenPowerOptFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwr/OffScreenPowerOptFeature.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/pwr/PSMPowerOptFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwr/PSMPowerOptFeature.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/pwr/PowerFeatureConfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwr/PowerFeatureConfig.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/pwr/StandbyFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwr/StandbyFeature.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/pwr/VendorScenarioPowerOptFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwr/VendorScenarioPowerOptFeature.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/pwr/VideoPowerOptFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwr/VideoPowerOptFeature.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/qguard.json:$(TARGET_COPY_OUT_VENDOR)/etc/qguard.json \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/qvr/cfg/519/0/65536/mtpkailua.txt:$(TARGET_COPY_OUT_VENDOR)/etc/qvr/cfg/519/0/65536/mtpkailua.txt \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/qvr/cfg/519/0/65536/mtpkailua_6dof_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qvr/cfg/519/0/65536/mtpkailua_6dof_config.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/qvr/cfg/519/0/65536/mtpkailua_qvr_3dof_tracker_config.txt:$(TARGET_COPY_OUT_VENDOR)/etc/qvr/cfg/519/0/65536/mtpkailua_qvr_3dof_tracker_config.txt \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/qvr/cfg/557/0/65536/mtplanai.txt:$(TARGET_COPY_OUT_VENDOR)/etc/qvr/cfg/557/0/65536/mtplanai.txt \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/qvr/cfg/557/0/65536/mtplanai_6dof_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qvr/cfg/557/0/65536/mtplanai_6dof_config.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/qvr/cfg/557/0/65536/mtplanai_qvr_3dof_tracker_config.txt:$(TARGET_COPY_OUT_VENDOR)/etc/qvr/cfg/557/0/65536/mtplanai_qvr_3dof_tracker_config.txt \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/qvr/qvr_hid_device_list.txt:$(TARGET_COPY_OUT_VENDOR)/etc/qvr/qvr_hid_device_list.txt \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/qvr/qvr_usb_device_list.txt:$(TARGET_COPY_OUT_VENDOR)/etc/qvr/qvr_usb_device_list.txt \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/qvr/qvrservice_config.txt:$(TARGET_COPY_OUT_VENDOR)/etc/qvr/qvrservice_config.txt \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/sap.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sap.conf \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/sec_config:$(TARGET_COPY_OUT_VENDOR)/etc/sec_config \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/seccomp_policy/atfwd@2.0.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/atfwd@2.0.policy \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/seccomp_policy/codec2.vendor.base-arm64.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/codec2.vendor.base-arm64.policy \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/seccomp_policy/codec2.vendor.ext-arm64.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/codec2.vendor.ext-arm64.policy \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/seccomp_policy/gnss@2.0-base.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-base.policy \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/seccomp_policy/gnss@2.0-edgnss-daemon.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-edgnss-daemon.policy \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/seccomp_policy/gnss@2.0-qsap-location.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-qsap-location.policy \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/seccomp_policy/gnss@2.0-xtra-daemon.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-xtra-daemon.policy \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/seccomp_policy/gnss@2.0-xtwifi-client.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-xtwifi-client.policy \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/seccomp_policy/qesdk.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qesdk.policy \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/seccomp_policy/qesdksec.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qesdksec.policy \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/seccomp_policy/qsap_qapeservice.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qsap_qapeservice.policy \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/seccomp_policy/qsap_sensors.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qsap_sensors.policy \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/seccomp_policy/qsap_voiceui.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qsap_voiceui.policy \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/seccomp_policy/qspm.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qspm.policy \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/seccomp_policy/qti-systemd.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qti-systemd.policy \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/seccomp_policy/qvr@2.0.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qvr@2.0.policy \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/seccomp_policy/qwesd@2.0.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qwesd@2.0.policy \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/seccomp_policy/sxr@2.0.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/sxr@2.0.policy \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/seccomp_policy/vendor.qti.hardware.dsp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/vendor.qti.hardware.dsp.policy \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/seccomp_policy/wfdhdcphalservice.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/wfdhdcphalservice.policy \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/seccomp_policy/wfdvndservice.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/wfdvndservice.policy \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/seccomp_policy/wifidisplayhalservice.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/wifidisplayhalservice.policy \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/smomo_setting.xml:$(TARGET_COPY_OUT_VENDOR)/etc/smomo_setting.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/snapdragon_color_libs_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/snapdragon_color_libs_config.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/ssg/ta_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/ssg/ta_config.json \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/ssg/tz_whitelist.json:$(TARGET_COPY_OUT_VENDOR)/etc/ssg/tz_whitelist.json \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/ueventd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/ueventd.rc \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/usecaseKvManager.xml:$(TARGET_COPY_OUT_VENDOR)/etc/usecaseKvManager.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/vmmgr.conf:$(TARGET_COPY_OUT_VENDOR)/etc/vmmgr.conf \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/wfdconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/wfdconfig.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/wifi/kiwi_v2/WCNSS_qcom_cfg.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/kiwi_v2/WCNSS_qcom_cfg.ini \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/wifi/passpointProfile.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/passpointProfile.conf \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/wifi/qca6750/WCNSS_qcom_cfg.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/qca6750/WCNSS_qcom_cfg.ini \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/wifi/vendor_cmd.xml:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/vendor_cmd.xml \
    vendor/xiaomi/sm8635-common/proprietary/vendor/etc/xtwifi.conf:$(TARGET_COPY_OUT_VENDOR)/etc/xtwifi.conf \
    vendor/xiaomi/sm8635-common/proprietary/vendor/firmware/CAMERA_ICP.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.elf \
    vendor/xiaomi/sm8635-common/proprietary/vendor/firmware/CAMERA_ICP_170.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP_170.elf \
    vendor/xiaomi/sm8635-common/proprietary/vendor/firmware/gen70900_aqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/gen70900_aqe.fw \
    vendor/xiaomi/sm8635-common/proprietary/vendor/firmware/gen70900_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/gen70900_sqe.fw \
    vendor/xiaomi/sm8635-common/proprietary/vendor/firmware/gen71100_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gen71100_gmu.bin \
    vendor/xiaomi/sm8635-common/proprietary/vendor/firmware/gen71100_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/gen71100_sqe.fw \
    vendor/xiaomi/sm8635-common/proprietary/vendor/firmware/gmu_gen70900.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gmu_gen70900.bin \
    vendor/xiaomi/sm8635-common/proprietary/vendor/firmware/qps615_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/qps615_fw.bin \
    vendor/xiaomi/sm8635-common/proprietary/vendor/gpu/kbc/sequence_manifest.bin:$(TARGET_COPY_OUT_VENDOR)/gpu/kbc/sequence_manifest.bin \
    vendor/xiaomi/sm8635-common/proprietary/vendor/gpu/kbc/unified_kbcs_64.bin:$(TARGET_COPY_OUT_VENDOR)/gpu/kbc/unified_kbcs_64.bin \
    vendor/xiaomi/sm8635-common/proprietary/vendor/gpu/kbc/unified_ksqs.bin:$(TARGET_COPY_OUT_VENDOR)/gpu/kbc/unified_ksqs.bin

PRODUCT_PACKAGES += \
    vendor.qti.diaghal-V1-ndk \
    btaudio_offload_if \
    camx.device-impl \
    camx.provider-impl \
    com.qti.camx.chiiqutils \
    com.qti.chiusecaseselector \
    com.qti.feature2.afbrckt \
    com.qti.feature2.anchorsync \
    com.qti.feature2.demux \
    com.qti.feature2.derivedoffline \
    com.qti.feature2.fusion \
    com.qti.feature2.generic \
    com.qti.feature2.gs.sm8650 \
    com.qti.feature2.hdr \
    com.qti.feature2.mcreprocrt \
    com.qti.feature2.memcpy \
    com.qti.feature2.metadataserializer \
    com.qti.feature2.mfsr \
    com.qti.feature2.ml \
    com.qti.feature2.mux \
    com.qti.feature2.offlinestatsregeneration \
    com.qti.feature2.qcfa \
    com.qti.feature2.rawhdr \
    com.qti.feature2.realtimeserializer \
    com.qti.feature2.rt \
    com.qti.feature2.rtmcx \
    com.qti.feature2.serializer \
    com.qti.feature2.statsregeneration \
    com.qti.feature2.stub \
    com.qti.feature2.swmf \
    com.qti.qseeaon \
    com.qti.qseeutils \
    com.qti.settings.sm8650 \
    com.qti.stats.common \
    com.qualcomm.mcx.distortionmapper \
    com.qualcomm.mcx.linearmapper \
    com.qualcomm.mcx.nonlinearmapper \
    com.qualcomm.mcx.policy.mfl \
    com.qualcomm.qti.dpm.api@1.0_vendor \
    com.qualcomm.qti.mcx.usecase.extension \
    com.xiaomi.camhal.extmodel.catch_log_sys \
    com.xiaomi.camhal.extmodel.ec_diag_sys \
    com.xiaomi.camhal.extmodel.ec_executor \
    com.xiaomi.camhal.extmodel.intent_aware_sys \
    com.xiaomi.camhal.overlap \
    com.xiaomi.camhal.submodel.camxfrag \
    com.xiaomi.camhal.submodel.chifrag \
    com.xiaomi.immunesystem.bigdata \
    com.xiaomi.immunesystem.bigdata2 \
    com.xiaomi.immunesystem.client \
    com.xiaomi.immunesystem.core \
    com.xiaomi.immunesystem.hook.camx \
    com.xiaomi.immunesystem.hook.chi \
    com.xiaomi.immunesystem.hook.mivi \
    com.xiaomi.immunesystem.hook.mtkhal \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libVkLayer_ADRENO_qprofiler \
    libq3dtools_adreno \
    libq3dtools_esx \
    android.hardware.bluetooth.audio-impl-qti \
    android.hardware.bluetooth@1.0-impl-qti \
    android.hardware.bluetooth@1.1-impl-qti \
    audio.bluetooth_qti.default \
    com.dsi.ant@1.0-impl \
    gyro_fusion_interface \
    libqtigatekeeper \
    sound_trigger.primary.pineapple \
    vendor.qti.hardware.alarm-impl \
    vendor.qti.hardware.bluetooth_audio@2.0-impl \
    vendor.qti.hardware.bluetooth_audio@2.1-impl \
    vendor.qti.hardware.bluetooth_sar@1.1-impl \
    vendor.qti.hardware.btconfigstore@1.0-impl \
    vendor.qti.hardware.btconfigstore@2.0-impl \
    vendor.qti.hardware.bttpi-impl \
    vendor.qti.hardware.capabilityconfigstore@1.0-impl \
    vendor.qti.hardware.qseecom@1.0-impl \
    vendor.qti.hardware.servicetrackeraidl-impl \
    vendor.qti.hardware.wifidisplaysession@1.0-impl \
    vendor.qti.memory.pasrmanager-impl \
    vulkan.adreno \
    immunesystem.db.sqlite3 \
    libAF \
    libAlacSwDec \
    libApeSwDec \
    libCB \
    libCneAppJni \
    libDISAlgos \
    libDcfHalFramework \
    libDcfHalLogger \
    libDcfHalQtiMutex \
    libDspIOProxy_stub \
    libEvrcSwCodec \
    libFace3DTA \
    libFace3D_hlos \
    libFileMux_proprietary \
    libFlacSwDec \
    libGPMTEEC_vendor \
    libGPTEE_vendor \
    libGPreqcancel \
    libGPreqcancel_svc \
    libHISCppAlgos \
    libIMTCppAlgos \
    libITT \
    libMapService \
    libMiMotion \
    libMiPhotoFilter \
    libMiVDR \
    libMiVideoFilter \
    libOISHighFPS \
    libOpenCL \
    libOpenCL_adreno \
    libPeripheralStateUtils \
    libPlatformValidatorShared \
    libQ6MSFR_manager_stub \
    libQEGA.qti \
    libQSEEComAPI \
    libQcelp13SwCodec \
    libQnnChrometraceProfilingReader \
    libQnnCpu \
    libQnnDsp \
    libQnnDspNetRunExtensions \
    libQnnDspV66CalculatorStub \
    libQnnDspV66Stub \
    libQnnGpu \
    libQnnGpuNetRunExtensions \
    libQnnGpuProfilingReader \
    libQnnHtp \
    libQnnHtpNetRunExtensions \
    libQnnHtpOptraceProfilingReader \
    libQnnHtpPrepare \
    libQnnHtpProfilingReader \
    libQnnHtpV68CalculatorStub \
    libQnnHtpV68Stub \
    libQnnHtpV69CalculatorStub \
    libQnnHtpV69Stub \
    libQnnHtpV73CalculatorStub \
    libQnnHtpV73Stub \
    libQnnHtpV75CalculatorStub \
    libQnnHtpV75Stub \
    libQnnJsonProfilingReader \
    libQnnModelDlc \
    libQnnSaver \
    libQnnSystem \
    libSNPE \
    libSNPESample \
    libScenescape \
    libSensorsInterface \
    libSnpeDspV66Stub \
    libSnpeHta \
    libSnpeHtpPrepare \
    libSnpeHtpV68CalculatorStub \
    libSnpeHtpV68Stub \
    libSnpeHtpV69Stub \
    libSnpeHtpV73Stub \
    libSnpeHtpV75Stub \
    libStereoRectifyWrapper \
    libTrustedInputAIDL \
    libTrustedInputUtils \
    libTrustedUIAIDL \
    libTxPwrJni \
    libVoiceSdk \
    libWlanServiceJni \
    libXMFaceFocus \
    lib_bt_lhdc \
    lib_misound_asc \
    libadaptlaunch \
    libadm \
    libadreno_app_profiles \
    libadreno_utils \
    libadsp_default_listener \
    libadsprpc \
    libagm \
    libagmmixer \
    libaidenoiser \
    libaidenoiserv2 \
    libaodoptfeature \
    libapengine \
    libappclassifier \
    libar-acdb \
    libar-gpr \
    libar-gsl \
    libarmemlog \
    libats \
    libaudio_log_utils \
    libaudiocloudctrl \
    libaudiofeaturestats \
    libbacklight-calib \
    libbatching \
    libbitmlengine \
    libbitmlenginev2 \
    libbluetooth_audio_session_aidl_qti \
    libbluetooth_audio_session_qti \
    libbluetooth_audio_session_qti_2_1 \
    libbt-hidlclient \
    libbtnv \
    libc++_shared \
    libcacertclient \
    libcalculator \
    libcalculator_htp \
    libcamdfx \
    libcameraopt \
    libcamerapostproc \
    libcamlog \
    libcamxcommonutils \
    libcamxexternalformatutils \
    libcamxfdengine \
    libcamxhwnodecontext \
    libcamxifestriping \
    libcamximageformatutils \
    libcamxncsdatafactory \
    libcamxqsatalgo \
    libcamxsettingsmanager \
    libcamxstatscore \
    libcamxswispiqmodule \
    libcamxswprocessalgo \
    libcamxtintlessalgo \
    libcapiv2svacnnvendor \
    libcapiv2svarnnvendor \
    libcapiv2udk7vendor \
    libcapiv2uvvendor \
    libcdfw \
    libcdfw_remote_api \
    libcdsp_default_listener \
    libcdsprpc \
    libceres \
    libcert_parse.wpa_s \
    libchifeature2 \
    libchilog \
    libclstc_algorithm_adapter \
    libclstc_gcp_adapter \
    libcne \
    libcneapiclient \
    libcneoplookup \
    libcneqmiutils \
    libcom.qti.chinodeutils \
    libcom.xiaomi.attribute \
    libcom.xiaomi.debug \
    libcom.xiaomi.ecoenginemonitor \
    libcom.xiaomi.eventcallback \
    libcom.xiaomi.grallocutils \
    libcom.xiaomi.mawutils \
    libcom.xiaomi.mawutilsold \
    libcom.xiaomi.metadatautils \
    libcom.xiaomi.pluginutils \
    libcom.xiaomi.qimagebuffer \
    libcom.xiaomi.sensorpolicy \
    libcom.xiaomi.signaltrigger \
    libcommonchiutils \
    libconfigdb \
    libcpion \
    libcv_common \
    libdapparamstorage \
    libdapparamstorage_3_12 \
    libdataitems \
    libdeccfg_3_12 \
    libdeflicker \
    libdfintf \
    libdiag \
    libdiagjni \
    libdigital-dimming \
    libdisp-aba \
    libdisplayconfig.qti \
    libdisplaydebug \
    libdisplayfeature \
    libdisplayfeatureservice \
    libdisplayqos \
    libdisplayskuutils \
    libdlbdsservice_3_12 \
    libdlbpreg \
    libdlbpreg_3_12 \
    libdmshal_3_12 \
    libdpmqmihal \
    libdpp_manager \
    libdpps \
    libdrmfs \
    libdrmtime \
    libdsd2pcm \
    libdsi_netctrl \
    libdsutils \
    libeai_fixed \
    libeai_float \
    libembmsservice \
    libengineplugin \
    libeva \
    libeva_util \
    libeye_tracking_dsp_sample_stub \
    libface3d_dev \
    libfastcvdsp_stub \
    libfastcvopt \
    libfastmessage \
    libfeutils \
    libfilefinder \
    libgame_enhance \
    libgamepoweroptfeature \
    libgdtap \
    libgeofencing \
    libgnss \
    libgnsspps \
    libgps.utils \
    libgpt \
    libgpu_tonemapper \
    libgpudataproducer \
    libgralloc.qti \
    libgralloccore \
    libgrallocutils \
    libgsl \
    libhalide_hexagon_host \
    libhdcp1prov \
    libhdcp2p2prov \
    libhdcpsrm \
    libhdr10plus \
    libhdr_backlight_adapter \
    libhdr_stub \
    libhdr_tm \
    libhis_face_tracking \
    libhistogram \
    libhme \
    libhta_hexagon_runtime_snpe \
    libiccprofile \
    libidl \
    libintervmipc \
    libipebpsstriping \
    libipebpsstriping170 \
    libipebpsstriping480 \
    libiqdbgmgr \
    libisphwsetting \
    libizat_client_api \
    libizat_core \
    libjnihelper \
    libjpege \
    libkaraokepal \
    libkcl \
    libkernelmanager \
    libkeymasterdeviceutils \
    libkeymasterprovision \
    libkeymasterutils \
    liblbs_core \
    liblearningmodule \
    liblightninglaunches \
    liblistensoundmodel2vendor \
    libllvm-glnext \
    libllvm-qcom \
    libllvm-qgl \
    liblmthermallistner \
    liblmutils-ns \
    libloadalgo_stub \
    libloc_api_v02 \
    libloc_api_wds \
    libloc_base_util \
    libloc_core \
    libloc_eng_hub \
    libloc_mq_client \
    libloc_qwes_iface \
    libloc_socket \
    libloc_util \
    liblocation_api \
    liblocation_api_msg \
    liblocation_client_api \
    liblocation_integration_api \
    liblocation_qesdk \
    liblocationservice \
    liblocationservice_glue \
    liblocdiagiface \
    liblowi_client \
    liblowi_common \
    liblowi_wifihal \
    liblx-ar_util \
    liblx-osal \
    libmapdata_api \
    libmasc \
    libmcs \
    libmctfengine_stub \
    libmdmdetect \
    libmdsprpc \
    libmemperfd \
    libmemutils \
    libmeters-ns \
    libmeters \
    libmfGhostDetection \
    libmfec \
    libmialgo \
    libmialgo_ai_vision \
    libmialgo_globalsaliency \
    libmialgo_video_colourkeeping \
    libmialgoengine \
    libmialgoengine_custom \
    libmibokeh_845_video \
    libmicamera_adapter \
    libmicamera_aidl_device \
    libmicamera_aidl_provider \
    libmicamera_aidl_utils \
    libmicamera_hal_core \
    libmicamera_hal_policy \
    libmifaceempty \
    libminikin.xiaomi \
    libminkdescriptor \
    libminksocket_vendor \
    libmips \
    libmis6 \
    libmis_platform \
    libmis_plugin_dummy \
    libmis_plugin_gme \
    libmis_plugin_his \
    libmis_plugin_morpho \
    libmis_plugin_qisv2 \
    libmis_plugin_qisv3 \
    libmisfpsop \
    libmisight \
    libmisops \
    libmisoundfx_ext \
    libmisoundsa \
    libmisoundsa_fx \
    libmispowerop \
    libmisr \
    libmlremosaicsnapshot \
    libmm-hdcpmgr \
    libmmcamera_bestats \
    libmmcamera_cac \
    libmmcamera_lscv35 \
    libmmcamera_pdpc \
    libmmosal_vendor \
    libmmrtpdecoder_vendor \
    libmmrtpencoder_vendor \
    libmorpho_ubwc \
    libmorpho_video_stabilizer \
    libmpbase \
    libnicm \
    libnicm_dsi \
    libnicm_interface \
    libnicm_internal \
    libnicm_modemproxy \
    libnicm_netlink \
    libnicm_recovery \
    libnicm_utils \
    libnicm_vh \
    libnspdependency \
    libnspdescriptorhandler \
    libnspdiag \
    libnspextensionloader \
    libnspframework \
    libnspframeworkcore \
    libnspframeworkcoreutility \
    libnspgraphing \
    libnspipc \
    libnsposal \
    libnspresource \
    libnspscheduler \
    libnspsession \
    libnspsuperresolutionserviceextension \
    libnsptransaction \
    libodmpoly \
    liboemcrypto \
    libofflinedebugdata \
    liboffscreenpoweroptfeature \
    libomp \
    libopencl_loader \
    libopencv \
    libopencv3a \
    libopestriping \
    libops \
    libos \
    libpal_net_if \
    libpasrutils \
    libpdmapper \
    libpdnotifier \
    libperfconfig \
    libperfgluelayer \
    libperfioctl \
    libperipheral_client \
    libpolygon \
    libpostprocinfo \
    libpowercallback \
    libpowercore \
    libprefapps \
    libprekill \
    libprocomp \
    libprotobuf-cpp-full-21.7 \
    libprotobuf-cpp-lite-21.7 \
    libpsmoptfeature \
    libq-perflog \
    libqape_oem_ext \
    libqapesdk \
    libqc2audio_base \
    libqc2audio_basecodec \
    libqc2audio_core \
    libqc2audio_hooks \
    libqc2audio_hwaudiocodec \
    libqc2audio_platform \
    libqc2audio_swaudiocodec \
    libqc2audio_utils \
    libqc2vppfilter \
    libqcbor \
    libqcc_file_agent \
    libqcc_sdk \
    libqcci_legacy \
    libqcmaputils \
    libqcodec2_base \
    libqcodec2_basecodec \
    libqcodec2_core \
    libqcodec2_cvpfilter \
    libqcodec2_filterbase \
    libqcodec2_hooks \
    libqcodec2_imgtxrfilter \
    libqcodec2_mockfilter \
    libqcodec2_platform \
    libqcodec2_psfilter \
    libqcodec2_srfilter \
    libqcodec2_streaminteg_filter \
    libqcodec2_utils \
    libqcodec2_v4l2codec \
    libqdcm-algo \
    libqdcm-json-mode-parser \
    libqdcm-mode-parser \
    libqdi \
    libqdutils \
    libqesdk2_0 \
    libqesdk_manager \
    libqesdoem_query_sys \
    libqisl \
    libqll \
    libqll10 \
    libqllengine \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_csvt_srvc \
    libqmi_encdec \
    libqmi_legacy \
    libqmiextservices \
    libqmiservices \
    libqrtr \
    libqrtrclient \
    libqseed3 \
    libqsegnet \
    libqservice \
    libqsh \
    libqshcamera \
    libqsocket \
    libqspm-mem-utils-vendor \
    libqti-iopd-client \
    libqti-iopd \
    libqti-perfd-client \
    libqti-perfd \
    libqti-qesdk-secure \
    libqti-util \
    libqti-utils \
    libqti_vndfwk_detect_vendor \
    libqtigefar \
    libqtikeymaster4 \
    libqtikeymint \
    libqvr_cam_cdsp_driver_stub \
    libqvr_cdsp_driver_stub \
    libqvr_eyetracking_plugin \
    libqvrcamera_client.qti \
    libqvrcameraplayback \
    libqvrservice \
    libqvrservice_client.qti \
    librcmask \
    libreffeature \
    libresampler \
    librpmb \
    libsagt \
    libscveCommon \
    libscveCommon_stub \
    libscveObjectSegmentation \
    libscveObjectTracker \
    libscveObjectTracker_stub \
    libsdedrm \
    libsdm-color \
    libsdm-colormgr-algo \
    libsdm-disp-vndapis \
    libsdmcore \
    libsdmdal \
    libsdmextension \
    libsdmutils \
    libsdsprpc \
    libsensor_calibration \
    libsensorcal \
    libsensorslog \
    libsfeShiftExtrapolation \
    libshadowhook \
    libshsc \
    libsi \
    libsilkyscrolls \
    libsimulation \
    libskewknob \
    libslimclient \
    libsmemlog \
    libsnapdragoncolor-manager \
    libsnapdragoncolor-qdcm \
    libsns_device_mode_stub \
    libsns_direct_channel_stub \
    libsns_dynamic_loader_stub \
    libsns_registry_skel \
    libsns_remote_proc_state_stub \
    libsnsapi-full \
    libsnsapi \
    libsnsdiaglog \
    libsnsutils \
    libsoc_helper \
    libspatializerparamstorage \
    libspatializerparamstorage_3_12 \
    libspcom \
    libspl \
    libsplh \
    libsrc_jni_getPasrService \
    libssc_default_listener \
    libssd \
    libstandbyfeature \
    libstreamparser \
    libsubsystem_control \
    libswregistrationalgo \
    libswspatializer_ext \
    libsxrservice \
    libsxrservice_client.qti \
    libsynergy_loc_api \
    libsynx \
    libsys_info_cache \
    libsysmon_cdsp_skel \
    libsystem_health_mon \
    libtaautoload \
    libtensorflowlite_c \
    libtestutils \
    libthermalclient \
    libthreadutils \
    libtime_genoff \
    libtinyxml2_1 \
    libtracker_6dof_impl \
    libtrustedapploader \
    libubifocus \
    libubwcp \
    libultrasound_notify \
    libvega_common \
    libvideoBokeh \
    libvideodiedobserver_vendor \
    libvideoml \
    libvideooptfeature \
    libvideotxr \
    libvideoutils \
    libvmfilexfer \
    libvmmem \
    libvppclient \
    libvppcommon \
    libvpphcp \
    libvpphvx \
    libvppimmotion \
    libvpplibrary \
    libvui_dmgr \
    libvui_dmgr_client \
    libvui_intf \
    libwfdcodecv4l2_proprietary \
    libwfdcommonutils_proprietary \
    libwfdconfigutils_proprietary \
    libwfddisplayconfig_vendor \
    libwfdhdcpcp \
    libwfdhdcpservice_proprietary \
    libwfdmminterface_proprietary \
    libwfdmmservice_proprietary \
    libwfdmmsrc_proprietary \
    libwfdmodulehdcpsession \
    libwfdrtsp_vendor \
    libwfdsessionmodule \
    libwfdsourcesession_proprietary \
    libwfdsourcesm_proprietary \
    libwfduibcinterface_vendor \
    libwfduibcsink_vendor \
    libwfduibcsinkinterface_vendor \
    libwfduibcsrc_vendor \
    libwfduibcsrcinterface_vendor \
    libwfdutils_proprietary \
    libwifiobserver \
    libwms \
    libwqe \
    libxlog \
    libxml \
    libxtadapter \
    qti.video.utils.videobufferlayout \
    libQ6MSFR_manager_skel \
    libVppAisQnnHtp \
    libVppFrcQnnHtp \
    libapn_dsp_skel \
    libbitml_nsp_73nb_skel \
    libbitml_nsp_75na_skel \
    libdpp_engine_skel \
    libdspCV_skel \
    libevadsp \
    libfastcvadsp \
    libfastcvdsp_skel \
    libhdr_skel \
    libhme_dsp_skel \
    libmobilenet_dsp_frc \
    libmobilenet_dsp_frc_networks \
    libnsp_ipc_cdsp_skel \
    libqsegnetengine_dsp_skel \
    libscveT2T_skel \
    libvpp_ais \
    libvpp_ais_networks \
    libvpp_frc \
    libvpp_svc_skel \
    libvpp_vqa_networks \
    libvpt_action_recognition \
    libworker_pool \
    sensors.qsh \
    libasphere \
    libdlbvol_3_12 \
    libhwdap_3_12 \
    libmisoundfx_n2 \
    libquasar \
    libshoebox \
    libspatializer \
    libspatializer_fx \
    libswgamedap_3_12 \
    libswspatializer_3_12 \
    vendor.display.color@1.0 \
    vendor.display.color@1.1 \
    vendor.display.color@1.2 \
    vendor.display.color@1.3 \
    vendor.display.color@1.4 \
    vendor.display.color@1.5 \
    vendor.display.postproc@1.0 \
    vendor.dolby.dms-V1-ndk \
    vendor.dolby.hardware.dms@2.0 \
    vendor.dolby_3_12.hardware.dms@2.0 \
    vendor.libdpmctmgr \
    vendor.libdpmfdmgr \
    vendor.libdpmframework \
    vendor.libdpmtcm \
    vendor.libmwqemiptablemgr \
    vendor.qti.data.factoryservice-V1-ndk \
    vendor.qti.data.mwqem@1.0 \
    vendor.qti.data.mwqemaidlservice-V1-ndk \
    vendor.qti.data.slm@1.0 \
    vendor.qti.diaghal@1.0_vendor \
    vendor.qti.gnss-V6-ndk \
    vendor.qti.hardware.AGMIPC@1.0-impl \
    vendor.qti.hardware.ListenSoundModel@1.0-impl \
    vendor.qti.hardware.ListenSoundModel@1.0 \
    vendor.qti.hardware.alarm-V1-ndk \
    vendor.qti.hardware.bluetooth_sar@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.1 \
    vendor.qti.hardware.bttpi-V3-ndk \
    vendor.qti.hardware.cacert@1.0 \
    vendor.qti.hardware.camera.aon-service-impl \
    vendor.qti.hardware.camera.offlinecamera-service-impl \
    vendor.qti.hardware.camera.postproc@1.0-service-impl \
    vendor.qti.hardware.data.cneaidlservice.internal.api-V1-ndk \
    vendor.qti.hardware.data.cneaidlservice.internal.constants-V1-ndk \
    vendor.qti.hardware.data.cneaidlservice.internal.server-V1-ndk \
    vendor.qti.hardware.data.dynamicdds@1.0 \
    vendor.qti.hardware.data.dynamicdds@1.1 \
    vendor.qti.hardware.data.dynamicddsaidlservice-V1-ndk \
    vendor.qti.hardware.data.flow@1.0 \
    vendor.qti.hardware.data.flow@1.1 \
    vendor.qti.hardware.data.flowaidlservice-V1-ndk \
    vendor.qti.hardware.data.iwlandata-V1-ndk \
    vendor.qti.hardware.data.latency@1.0 \
    vendor.qti.hardware.data.lce@1.0 \
    vendor.qti.hardware.data.lceaidlservice-V1-ndk \
    vendor.qti.hardware.data.qmiaidlservice-V1-ndk \
    vendor.qti.hardware.dpmaidlservice-V1-ndk_vendor \
    vendor.qti.hardware.dpmservice@1.0_vendor \
    vendor.qti.hardware.dpmservice@1.1 \
    vendor.qti.hardware.dsp@1.0 \
    vendor.qti.hardware.embmssl@1.0 \
    vendor.qti.hardware.embmssl@1.1 \
    vendor.qti.hardware.embmsslaidl-V1-ndk \
    vendor.qti.hardware.factory-V1-ndk \
    vendor.qti.hardware.factory@1.0 \
    vendor.qti.hardware.factory@1.1 \
    vendor.qti.hardware.fm@1.0 \
    vendor.qti.hardware.hexlp-V1-ndk \
    vendor.qti.hardware.iop@1.0 \
    vendor.qti.hardware.iop@2.0 \
    vendor.qti.hardware.limits@1.0 \
    vendor.qti.hardware.limits@1.1 \
    vendor.qti.hardware.limits@1.2 \
    vendor.qti.hardware.mwqemadapter@1.0 \
    vendor.qti.hardware.mwqemadapteraidlservice-V1-ndk \
    vendor.qti.hardware.pal@1.0-impl \
    vendor.qti.hardware.perf2-V1-ndk \
    vendor.qti.hardware.power.powermodule-V1-ndk \
    vendor.qti.hardware.qccsyshal@1.0_vendor \
    vendor.qti.hardware.qccsyshal@1.1_vendor \
    vendor.qti.hardware.qccsyshal@1.2_vendor \
    vendor.qti.hardware.qconfig-V1-ndk \
    vendor.qti.hardware.qconfig-V3-ndk \
    vendor.qti.hardware.qdutils_disp@1.0 \
    vendor.qti.hardware.qseecom-V1-ndk \
    vendor.qti.hardware.qseecom@1.0 \
    vendor.qti.hardware.qteeconnector@1.0 \
    vendor.qti.hardware.qxr-V1-ndk \
    vendor.qti.hardware.secureprocessor.common-V1-ndk \
    vendor.qti.hardware.secureprocessor.common-helper \
    vendor.qti.hardware.secureprocessor.common@1.0-helper \
    vendor.qti.hardware.secureprocessor.common@1.0 \
    vendor.qti.hardware.secureprocessor.config-V1-ndk \
    vendor.qti.hardware.secureprocessor.config@1.0 \
    vendor.qti.hardware.secureprocessor.device-V1-ndk \
    vendor.qti.hardware.secureprocessor.device@1.0 \
    vendor.qti.hardware.sensorscalibrate-V1-ndk \
    vendor.qti.hardware.slmadapter@1.0 \
    vendor.qti.hardware.trustedui-V1-ndk \
    vendor.qti.hardware.vpp-V1-ndk \
    vendor.qti.hardware.vpp@1.1 \
    vendor.qti.hardware.vpp@1.2 \
    vendor.qti.hardware.vpp@1.3 \
    vendor.qti.hardware.wifidisplaysession@1.0_vendor \
    vendor.qti.hardware.wifidisplaysessionl@1.0-halimpl \
    vendor.qti.hardware.wigig.netperftuner@1.0 \
    vendor.qti.latency@2.0 \
    vendor.qti.latency@2.1 \
    vendor.qti.latency@2.2 \
    vendor.qti.latencyaidlservice-V1-ndk \
    vendor.qti.memory.pasrmanager-V1-ndk \
    vendor.qti.memory.pasrmanager@1.0 \
    vendor.qti.memory.pasrmanager@1.1 \
    vendor.qti.power.pasrmanager@1.0 \
    vendor.qti.qccvndhal_aidl-V1-ndk_vendor \
    vendor.qti.qccvndhal_aidl-halimpl \
    vendor.qti.qegahal-V1-ndk_platform \
    vendor.qti.qesdhal-impl \
    vendor.qti.qesdhal@1.0 \
    vendor.qti.qesdhal@1.1 \
    vendor.qti.qesdhal@1.2 \
    vendor.qti.qesdhal@1.3 \
    vendor.qti.qesdhalaidl-V2-ndk \
    vendor.qti.qesdsys-V3-ndk \
    vendor.qti.qesdsys-V4-ndk \
    vendor.qti.qspmhal-V1-ndk \
    vendor.qti.qspmhal-impl \
    vendor.qti.qspmhal@1.0 \
    vendor.qti.voiceprint@1.0 \
    vendor.xiaomi.hardware.aidl.intentaware-V1-impl \
    vendor.xiaomi.hardware.aidl.intentaware-V1-ndk_platform \
    vendor.xiaomi.hardware.aidlbgservice-V1-impl \
    vendor.xiaomi.hardware.aidlbgservice-V1-ndk \
    vendor.xiaomi.hardware.aon-V1-ndk \
    vendor.xiaomi.hardware.bgservice@1.0-impl \
    vendor.xiaomi.hardware.bgservice@1.0 \
    vendor.xiaomi.hardware.camera.companion-V1-ndk \
    vendor.xiaomi.hardware.camera.companion-impl \
    vendor.xiaomi.hardware.camera.injection-V1-ndk \
    vendor.xiaomi.hardware.camera.injection-client \
    vendor.xiaomi.hardware.camera.injection-service \
    vendor.xiaomi.hardware.camera.synthetic-V1-ndk \
    vendor.xiaomi.hardware.camera.synthetic-impl \
    vendor.xiaomi.hardware.display.mihwcextension-V1-ndk \
    vendor.xiaomi.hardware.displayfeature_aidl-V2-ndk \
    vendor.xiaomi.hardware.quickcamera-V1-ndk \
    vendor.xiaomi.hardware.seccam-V1-ndk \
    vendor.xiaomi.hw.touchfeature-V1-ndk_platform \
    vendor.xiaomi.sensor.citsensorservice-V1-ndk \
    xiaomi.system.hypsys.common-V1-ndk \
    chre_qsh_shim \
    libCalculator_skel \
    libDspIOProxy_skel \
    libQnnHtpV73 \
    libQnnHtpV73QemuDriver \
    libQnnHtpV73Skel \
    libQnnHtpV75 \
    libQnnHtpV75Skel \
    libQnnSaver \
    libQnnSystem \
    libSnpeHtpV73Skel \
    libSnpeHtpV75Skel \
    libadsp_jpege_skel \
    libarc_htp_driver_skel \
    libbitml_nsp_skel \
    libdsp_streamer_binning \
    libdsp_streamer_qvrcam_receiver \
    libeye_tracking_dsp_sample_skel \
    libhalide_hexagon_remote_skel \
    libmctfengine_skel \
    libmialgo_basic_cdsp_skel \
    libmialgo_rfs_cdsp_skel \
    libmlawbpostproc_dsp_skel \
    libqvr_3dof_tracker_skel \
    libqvr_cam_dsp_driver_skel \
    libqvr_dsp_driver_skel \
    libtracker_6dof_skel_8450 \
    nearby.napp_header \
    nearby \
    com.qualcomm.qti.dpm.api@1.0 \
    libdiag_system \
    libdpmctmgr \
    libdpmfdmgr \
    libdpmframework \
    libdpmtcm \
    libmmosal \
    libmmparser_lite \
    libmmrtpdecoder \
    libmmrtpencoder \
    libqcc \
    libqcc_file_agent_sys \
    libqccdme \
    libqccfileservice \
    libwfdavenhancements \
    libwfdclient \
    libwfdcommonutils \
    libwfdconfigutils \
    libwfddisplayconfig \
    libwfdmminterface \
    libwfdmmsink \
    libwfdmmsrc_system \
    libwfdnative \
    libwfdrtsp \
    libwfdservice \
    libwfdsinksm \
    libwfduibcinterface \
    libwfduibcsink \
    libwfduibcsinkinterface \
    libwfduibcsrc \
    libwfduibcsrcinterface \
    vendor.qti.diaghal@1.0 \
    vendor.qti.hardware.dpmaidlservice-V1-ndk \
    vendor.qti.hardware.dpmservice@1.0 \
    vendor.qti.hardware.qccsyshal@1.0 \
    vendor.qti.hardware.qccsyshal@1.1 \
    vendor.qti.hardware.qccsyshal@1.2-halimpl \
    vendor.qti.hardware.qccsyshal@1.2 \
    vendor.qti.hardware.qccvndhal@1.0 \
    vendor.qti.hardware.wifidisplaysession@1.0 \
    vendor.qti.hardware.wifidisplaysession_aidl-V1-ndk \
    vendor.qti.qccsyshal_aidl-V1-ndk \
    vendor.qti.qccsyshal_aidl-halimpl \
    vendor.qti.qccvndhal_aidl-V1-ndk \
    android.hardware.gnss-aidl-impl-qti \
    com.xiaomi.camdfx \
    consumerir.qcom \
    displayfeature.default \
    libAncHumanVideoBokehV4 \
    libFaceCenterAlgo \
    libIntelligentFocus \
    libMiDispDevManager \
    libMiEmojiEffect \
    libMiStereoFactoryCalibAnalyzeBin_qual \
    libTrueSight \
    libadaptivehdr \
    libalAI_Seg_CFR \
    libalCFR \
    libalLDC \
    libanc_edof_checker \
    libanc_objdetection \
    libanc_single_bokeh \
    libanc_single_bokeh_rear \
    libanc_single_rt_bokeh \
    libanc_supermoon \
    libarcsoft_hdr_detection \
    libarcsoft_high_dynamic_range \
    libarcsoft_low_light_hdr \
    libarcsoft_mf_superresolution \
    libarcsoft_qnnhtp \
    libarcsoft_raw_sr_detection \
    libarcsoft_super_night_detection \
    libarcsoft_super_night_raw \
    libarcsoft_turbo_hdr_detection \
    libarcsoft_turbo_sr_detection \
    libaudioroute_ext \
    libcamera_scene \
    libclient2slpi.notifier \
    libcolortempmode \
    libcrussp \
    libdisplaycount \
    libdisplaylog \
    libdither \
    libdlrmsc \
    libellv \
    libeyecare \
    libflatmode \
    libfpsmonitor \
    libhandgesture.arcsoft \
    libhistprocess \
    liblocalFlickerDet \
    libmi-stc-HW-modulate \
    libmiBrightness \
    libmiClstc \
    libmiSensorCtrl \
    libmiStereoCalibLib_qual \
    libmiXmlParser \
    libmi_dspp \
    libmiai_deblur \
    libmiaio_head_seg \
    libmialgo_ie_capture \
    libmialgo_sd \
    libmialgo_utils \
    libmialgo_video_seg_depth \
    libmieventnodewatch \
    libmiocr \
    libmiphone_capture_bokeh \
    libpaperMode \
    libportrait_repair_qnn \
    libremosaic_wrapper \
    libremosaiclib \
    librfs_warp \
    librhytheyecare \
    libsdr2hdr \
    libsre \
    libsupermoon \
    libtensorflowlite_touch_c \
    libtouchsensor \
    libtruetone \
    libvideomode \
    libvoipspacespeech \
    libvpnr_enroll_pad \
    libvpnr_pad \
    libwa_widelens_undistort \
    libwrapper_dlengine \
    libwvkeybox \
    libxmi_hdr_checker \
    libxmi_slow_motion_mein \
    vendor.xiaomi.hardware.mediaeventgatherservice-V1-ndk \
    libmialgo_ell_cdsp_skel \
    com.google.android.widevine.nonupdatable \
    CACertService \
    CneApp \
    IWlanService \
    TimeService \
    com.qualcomm.qti.gpudrivers.pineapple.api34 \
    WfdService \
    dpmserviceapp \
    WfdCommon \
    com.qti.dpmframework \
    dpmapi \
    android.hardware.drm-service.xml \
    android.hardware.security.keymint-service-qti.xml \
    bttpi-saidl.xml \
    c2_manifest_vendor.xml \
    c2_manifest_vendor_audio.xml \
    datafactoryservice-saidl.xml \
    dms-service.xml \
    dpm-saidl.xml \
    mwqem-saidl.xml \
    qesdk-manager.xml \
    vendor.qti.camera.postproc-impl.xml \
    vendor.qti.camera.provider.xml \
    vendor.qti.diag.hal.service.xml \
    vendor.qti.hardware.alarm.xml \
    vendor.qti.hardware.embmssl.xml \
    vendor.qti.hardware.factory.ifactory.xml \
    vendor.qti.hardware.hexlp-service.xml \
    vendor.qti.hardware.limits-service.xml \
    vendor.qti.hardware.perf2.xml \
    vendor.qti.hardware.power.powermodule.xml \
    vendor.qti.hardware.qseecom@1.0-service.xml \
    vendor.qti.hardware.qxr-service.xml \
    vendor.qti.hardware.secureprocessor.xml \
    vendor.qti.hardware.sensorscalibrate.xml \
    vendor.qti.hardware.servicetrackeraidl-service.xml \
    vendor.qti.hardware.trustedui-aidl-service.xml \
    vendor.qti.hardware.vpp-service.xml \
    vendor.qti.hardware.wifidisplaysession-service.xml \
    vendor.qti.memory.pasrmanager-service.xml \
    vendor.qti.qccvndhal_aidl-service.xml \
    vendor.qti.qspmhal-service.xml \
    vendor.xiaomi.camera.aon-impl.xml \
    vendor.xiaomi.hardware.aidl.intentaware-service.xml \
    vendor.xiaomi.hardware.aidlbgservice-service.xml \
    vendor.xiaomi.hardware.displayfeature_aidl-service.xml \
    vendor.xiaomi.hardware.dynamiccameraserver.xml \
    vendor.xiaomi.hardware.quickcamera.xml \
    vendor.qti.qccsyshal_aidl-service.xml \
    vendor.xiaomi.hw.touchfeature-service.xml \
    vendor.xiaomi.sensor.citsensorservice.aidl.xml \
    adpl \
    adsprpcd \
    batterysecret \
    cdsprpcd \
    cnd \
    cnss-daemon \
    diag-router \
    displayfeature \
    dpmQmiMgr \
    dspservice \
    early_eth \
    edgnss-daemon \
    embmsslServer \
    engine-service \
    feature_enabler_client \
    hdcp1prov \
    hdcp2p2prov \
    hexlpservice \
    android.hardware.bluetooth@1.1-service-qti \
    android.hardware.gatekeeper-service-qti \
    android.hardware.security.keymint-service-qti \
    pasrknob \
    sxrservice \
    vendor.dolby.dms.service \
    vendor.qti.camera.provider-service_64 \
    vendor.qti.hardware.alarm-service \
    vendor.qti.hardware.capabilityconfigstore@1.0-service \
    vendor.qti.hardware.display.color-service \
    vendor.qti.hardware.display.composer-service \
    vendor.qti.hardware.factory-service \
    vendor.qti.hardware.factory@1.0-service \
    vendor.qti.hardware.iop@2.0-service \
    vendor.qti.hardware.limits@1.2-service \
    vendor.qti.hardware.perf2-hal-service \
    vendor.qti.hardware.qseecom@1.0-service \
    vendor.qti.hardware.secureprocessor \
    vendor.qti.hardware.secureprocessor@1.0 \
    vendor.qti.hardware.sensorscalibrate-service \
    vendor.qti.hardware.servicetrackeraidl-service \
    vendor.qti.hardware.trustedui-aidl-service-qti \
    vendor.qti.media.c2@1.0-service \
    vendor.qti.media.c2audio@1.0-service \
    vendor.qti.memory.pasrmanager-service \
    vendor.qti.psiclient@1.0-service \
    vendor.xiaomi.hardware.displayfeature_aidl-service \
    vendor.xiaomi.hardware.dynamiccameraserver \
    init.class_main \
    init.crda \
    init.kernel.extra_free_kbytes \
    init.kernel.post_boot-cliffs \
    init.kernel.post_boot-cliffs_2_2_1 \
    init.kernel.post_boot-cliffs_3_3_1 \
    init.kernel.post_boot-cliffs_default_3_4_1 \
    init.kernel.post_boot-memory \
    init.kernel.post_boot \
    init.mdm \
    init.qcom.class_core \
    init.qcom.early_boot \
    init.qcom.post_boot \
    init.qcom.sdio \
    init.qcom.sensors \
    init.qcom \
    init.qti.graphics \
    init.qti.kernel \
    init.qti.media \
    init.qti.qcv \
    init.qti.write \
    irsc_util \
    loadalgo \
    loc_launcher \
    lowi-server \
    mi_thermald \
    mlid \
    mmid \
    pd-mapper \
    pm-proxy \
    pm-service \
    port-bridge \
    power_off_alarm \
    poweropt-service \
    ppd \
    qcc-vendor \
    qdcmss \
    qesdk-manager \
    qguard \
    qlm-service \
    qmipriod \
    qrtr-cfg \
    qrtr-lookup \
    qrtr-ns \
    qsap_qapeservice \
    qsap_sensors \
    qsap_voiceui \
    qseecomd \
    qti \
    qvrcameratest \
    qvrdatacapture \
    qvrdatalogger \
    qvrdatauploader \
    qvrservicetest \
    qwesd \
    rmt_storage \
    sensors.qti \
    shsusrd \
    slim_daemon \
    sscrpcd \
    ssgqmigd \
    ssgtzd \
    ssr_diag \
    ssr_setup \
    subsystem_ramdump \
    system_dlkm_modprobe \
    tftp_server \
    time_daemon \
    trusteduilistener \
    ubwcconvert \
    vendor.dpmd \
    vendor.qti.qspmhal-service \
    vendor_modprobe \
    vmmgr \
    vppservice \
    wfdhdcphalservice \
    wfdvndservice \
    wifidisplayhalservice \
    xtra-daemon \
    xtwifi-client \
    dpmd \
    qccsyshal_aidl-service \
    tcmd \
    wfdservice64 \
    vendor.xiaomi.hw.touchfeature-service \
    vendor.xiaomi.sensor.citsensorservice.aidl \
    init.mi.serial \
    touch_report_debug \
    toucheventcheck

PRODUCT_PACKAGES += \
    system_ext_priv-app_WfdService_lib_arm64_libwfdnative_so \
    vendor_lib64_libEGL_adreno_so \
    vendor_lib64_libGLESv2_adreno_so \
    vendor_lib64_libq3dtools_adreno_so \
    vendor_lib64_soundfx_libmisoundfx_so

PRODUCT_BOOT_JARS += \
    WfdCommon
